version: '3.4'

services:
  pruebadb:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04

  backend.api:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: BACKEND/Dockerfile

volumes:
  sqlserver_prueba:
